### ISSUE TITLE
fail build with miniupnp 1.9.20151008-1 (attach patch)

### ISSUE THREAD

**Issue by sl1pkn07** [ygrek/mldonkey#13]
Hi. mldonkey(git) stop build with miniupnp 1.9.20151008-1

    ocamlopt.opt -inline 10 -w -3    -I src/utils/extlib  -I src/utils/cdk  -I src/utils/bitstring  -I src/utils/lib  -I src/utils/ocamlrss  -I src/utils/xml-light  -I src/utils/net  -I tools  -I src/daemon/common  -I src/daemon/driver  -I src/utils/mp3tagui  -I src/config/unix  -I src/networks/donkey -I +camlp4 -c         src/utils/ocamlrss/rss_date.ml
    src/utils/net/upnp_stubs.c: En la función ‘upnpPulse’:
    src/utils/net/upnp_stubs.c:643:19: error: faltan argumentos para la función ‘upnpDiscover’
             devlist = upnpDiscover( 2000, NULL, NULL, 0, 0, 0 );
                       ^
the patch is https://projects.archlinux.org/svntogit/community.git/tree/trunk/fix_upnpDiscover.patch?h=packages/mldonkey&id=9780becc5e24acd9709ab2ea900b7458e118bdc0

thanks to Anatol Pomozov from Archlinux

**Comment by ygrek** [comment]
Thanks for the report

PS
Looks like archlinux patch is wrong, quoting the doc
> TTL should default to 2
