### ISSUE TITLE
UPNP build error

### ISSUE THREAD

**Issue by ogarcia** [ygrek/mldonkey#101]
Arch Linux with libnatpmp-20230423-2 and miniupnpc-2.2.8-1:
```
src/utils/net/upnp_stubs.c: In function ‘upnpPulse’:
src/utils/net/upnp_stubs.c:659:41: error: too few arguments to function ‘UPNP_GetValidIGD’
  659 |         if( UPNP_IGD_VALID_CONNECTED == UPNP_GetValidIGD( devlist, &map->upnpUrls, &map->upnpData,
      |                                         ^~~~~~~~~~~~~~~~
```

This problem occurred after upgrading miniupnpc from 2.2.7-2 to 2.2.8-1 so the culprit is this update.

**Comment by FabioLolix** [comment]
In the Arch AUR pkgbuild the pro is now avoided using 

`sed -i 's/sizeof( map->lanaddr )/sizeof( map->lanaddr ), NULL , 0/g' src/utils/net/upnp_stubs.c` 

as suggested here

* https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=ef78ef66f5a4b4c92e646a45ebd20c06c756eeb3
* https://aur.archlinux.org/packages/mldonkey#comment-981166
